# 超参数配置

dev_directory: C:\data\音频素材\异音检测\dev_data
#dev_directory :  E:\音频素材\DCASE\dcase2020t2\dev_data
eval_directory: C:\data\音频素材\异音检测\eval_data
model_directory: ./model
result_directory: ./result
result_file: result.csv

max_fpr: 0.1

feature:
  n_mels: 128
  frames: 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

anomaly_threshold: 14
fit:
  compile:
    optimizer: adam
    loss: mean_squared_error
  epochs: 100
  batch_size: 512
  shuffle: True
  validation_split: 0.1
  verbose: 1
