from BaseASD.DenseAE.DenseAE_interface import DenseAEInterface
from BaseASD.ConvolutionalAE.CAE_interface import CAEInterface
from BaseASD.VAE.VAE_interface import VAEInterface
from BaseASD.AEGAN.AeGan_interface import AEGANInterface
from BaseASD.DifferNet.DifferNet_interface import DifferNetInterface