# 配置文件在这里修改，避免硬编码

ref_file: ref/渡口片段10s.wav
example_audio_file: ref/asd_src_audio.wav
pic_output_dir: slice
model_ckpts:
  dinomaly:
    dinov2:
      small:
      base:
      large:
    dinov3:
      small: /home/zhouchenghao/PycharmProjects/ASD_for_SPK/Dinomaly/saved_results/dinomaly_dinov3_small_dk_qzgy_epoch_1000_Sat Mar 28 22:35:13 2026.pth
      large:


model_threshold:
  dinomaly:
    dinov2:
      small: 0.02
      base: 0.02
      large: 0.02
    dinov3:
      small: 0.033
      base: 0.033
      large: 0.033
server:
  server_name: 0.0.0.0
  port: 8002
  share: False
  inbrowser: True

# 环境变量
environments:
    DINOMALY_ENCODER_DIR: /home/zhouchenghao/PycharmProjects/ASD_for_SPK/Dinomaly/weights
    CUDA_VISIBLE_DEVICES: 0
